<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \ClawRock\Debug\Model\Collector\CacheCollector $collector */
$collector = $block->getCollector();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?= /* @noEscape */ $collector->getName() ?>">
    <a target="_blank" href="<?= $block->escapeUrl($block->getProfilerUrl()); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/collector/cache.svg'); ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Cache')) ?>"/>
            <span class="sf-toolbar-value"><?= /* @noEscape */ $collector->getTotalTime(); ?> ms</span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group">
            <?php foreach ($collector->getCacheList() as $cache): ?>
                <div class="sf-toolbar-info-piece">
                    <b><?= /* @noEscape */ $cache->getCacheType(); ?></b>
                    <?php if ($cache->getStatus() === 1): ?>
                        <?php if ($collector->isInvalidated($cache->getId())): ?>
                            <span class="sf-toolbar-status sf-toolbar-status-yellow"><?= $block->escapeHtml(__('INV')); ?></span>
                        <?php else: ?>
                            <span class="sf-toolbar-status sf-toolbar-status-green"><?= $block->escapeHtml(__('YES')); ?></span>
                        <?php endif; ?>
                        &nbsp;
                        <a href="#"
                           data-url="<?= $block->escapeUrl($block->getUrl('_debug/cache/clean', ['type' => $cache->getId()])) ?>"
                           class="ajax-action"><?= $block->escapeHtml(__('Clean')); ?></a> /
                        <a href="#"
                           data-url="<?= $block->escapeUrl($block->getUrl('_debug/cache/disable', ['type' => $cache->getId()])) ?>"
                           class="ajax-action"><?= $block->escapeHtml(__('Disable')); ?></a>
                    <?php else:?>
                        <span class="sf-toolbar-status"><?= $block->escapeHtml(__('NO')); ?></span>
                        &nbsp;
                        <a href="#"
                           data-url="<?= $block->escapeUrl($block->getUrl('_debug/cache/enable', ['type' => $cache->getId()])) ?>"
                           class="ajax-action"><?= $block->escapeHtml(__('Enable')); ?></a>
                    <?php endif;?>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="sf-toolbar-info-group" >
            <div class="sf-toolbar-info-piece" style="text-align: right; display: block;">
                <a href="#" data-url="<?= $block->escapeUrl($block->getUrl('_debug/cache/clean')) ?>" class="ajax-action">
                    <?= $block->escapeHtml(__('Clean')); ?>
                </a> /
                <a href="#" data-url="<?= $block->escapeUrl($block->getUrl('_debug/cache/flush')) ?>" class="ajax-action">
                    <?= $block->escapeHtml(__('Flush')); ?>
                </a>
            </div>
        </div>
        <div class="sf-toolbar-info-group" >
            <div class="sf-toolbar-info-piece">
                <b><?= $block->escapeHtml(__('Cache calls')); ?></b>
                <span class="sf-toolbar-status"><?= /* @noEscape */ $collector->getCacheCalls() ?></span>
            </div>
            <div class="sf-toolbar-info-piece">
                <b><?= $block->escapeHtml(__('Time')); ?></b>
                <span><?= /* @noEscape */ $collector->getTotalTime() ?> ms</span>
            </div>
        </div>
    </div>
</div>
