<?php
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \ClawRock\Debug\Model\Collector\DatabaseCollector $collector
 */
$collector = $block->getCollector();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?= /* @noEscape */ $collector->getName() ?> sf-toolbar-status-normal">
    <a target="_blank" href="<?= $escaper->escapeUrl($block->getProfilerUrl()); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/collector/database.svg'); ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Database')) ?>"/>
            <span class="sf-toolbar-value"><?= /* @noEscape */ $collector->getQueriesCount() ?></span>
            <span class="sf-toolbar-info-piece-additional-detail">
                <span class="sf-toolbar-label"><?= $escaper->escapeHtml(__('in')); ?></span>
                <span class="sf-toolbar-value"><?= /* @noEscape */ $collector->getTotalTime() ?></span>
                <span class="sf-toolbar-label">ms</span>
            </span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <strong><?= $escaper->escapeHtml(__('Database Queries')); ?></strong>
            <span class="sf-toolbar-status "><?= /* @noEscape */ $collector->getQueriesCount() ?></span>
        </div>
        <div class="sf-toolbar-info-piece">
            <strong><?= $escaper->escapeHtml(__('Duplicated Queries')); ?></strong>
            <span class="sf-toolbar-status sf-toolbar-status-<?= /* @noEscape */ $collector->getStatus() ?>">
                <?= count($collector->getDuplicatedQueries()) ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <strong><?= $escaper->escapeHtml(__('Query time')); ?></strong>
            <span><?= /* @noEscape */ $collector->getTotalTime() ?> ms</span>
        </div>
    </div>
</div>
