<?php
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \ClawRock\Debug\Model\Collector\PluginCollector $collector
 */
$collector = $block->getCollector();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?= /* @noEscape */ $collector->getName() ?>">
    <a target="_blank" href="<?= $escaper->escapeUrl($block->getProfilerUrl()); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/collector/plugin.svg'); ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Plugin')) ?>"/>
            <span class="sf-toolbar-value"><?= /* @noEscape */ $collector->getPluginsCount() ?></span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <strong><?= $escaper->escapeHtml(__('Before plugins')); ?></strong>
            <span class="sf-toolbar-status">
                 <?= /* @noEscape */ $collector->getBeforePluginsCount() ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <strong><?= $escaper->escapeHtml(__('Around plugins')); ?></strong>
            <span class="sf-toolbar-status">
                 <?= /* @noEscape */ $collector->getAroundPluginsCount() ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <strong><?= $escaper->escapeHtml(__('After plugins')); ?>'</strong>
            <span class="sf-toolbar-status">
                 <?= /* @noEscape */ $collector->getAfterPluginsCount() ?>
            </span>
        </div>
    </div>
</div>
