<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector\Database $block */
/** @var \ClawRock\Debug\Model\DataCollector\DatabaseDataCollector $collector */
$collector = $block->getCollector();
?>
<div style="float:left; width: 50%">
    <h2>Query metrics</h2>
    <div class="metrics">
        <div class="metric">
            <span class="value"><?php echo $collector->getQueryCount() ?></span>
            <span class="label">Database queries</span>
        </div>
        <div class="metric">
            <span class="value"><?php echo $block->countDuplicatedQueries(); ?></span>
            <span class="label">Duplicated queries</span>
        </div>
        <div class="metric">
            <span class="value"><?php echo sprintf('%0.2f', $collector->getTotalTime()) ?> ms</span>
            <span class="label">Query time</span>
        </div>
    </div>
</div>
<div style="clear: both;"></div>
<h2>Queries</h2>
<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title">All<span class="badge"><?php echo $collector->getQueryCount() ?></span></h3>
        <div class="tab-content">
            <?php echo $block->renderQueryTable('all', $block->getQueries()); ?>
        </div>
    </div>
    <?php if ($block->countDuplicatedQueries()): ?>
        <div class="tab">
            <h3 class="tab-title">Duplicated queries<span class="badge"><?php echo $block->countDuplicatedQueries(); ?></span></h3>
            <div class="tab-content"><?php echo $block->renderQueryTable('duplicated', $block->getDuplicatedQueries()); ?></div>
        </div>
    <?php endif; ?>
    <?php if ($block->countSelect()): ?>
        <div class="tab">
            <h3 class="tab-title">SELECT <span class="badge"><?php echo $block->countSelect(); ?></span></h3>
            <div class="tab-content"><?php echo $block->renderQueryTable('select', $block->getSelectQueries()); ?></div>
        </div>
    <?php endif; ?>
    <?php if ($block->countInsert()): ?>
        <div class="tab">
            <h3 class="tab-title">INSERT <span class="badge"><?php echo $block->countInsert(); ?></span></h3>
            <div class="tab-content"><?php echo $block->renderQueryTable('insert', $block->getInsertQueries()); ?></div>
        </div>
    <?php endif; ?>
    <?php if ($block->countUpdate()): ?>
        <div class="tab">
            <h3 class="tab-title">UPDATE <span class="badge"><?php echo $block->countUpdate(); ?></span></h3>
            <div class="tab-content"><?php echo $block->renderQueryTable('update', $block->getUpdateQueries()); ?></div>
        </div>
    <?php endif; ?>
    <?php if ($block->countDelete()): ?>
        <div class="tab">
            <h3 class="tab-title">DELETE <span class="badge"><?php echo $block->countDelete(); ?></span></h3>
            <div class="tab-content"><?php echo $block->renderQueryTable('delete', $block->getDeleteQueries()); ?></div>
        </div>
    <?php endif; ?>
    <?php if ($block->countOther()): ?>
        <div class="tab">
            <h3 class="tab-title">Other <span class="badge"><?php echo $block->countOther(); ?></span></h3>
            <div class="tab-content"><?php echo $block->renderQueryTable('select', $block->getOtherQueries()); ?></div>
        </div>
    <?php endif; ?>
</div>
<style>
    tr.sf-toggle-content.sf-toggle-visible {
        display: table-row !important;
    }
    td > .context > strong {
        display: none;
    }
    .hidden {
        display: none;
    }
    .queries-table td, .queries-table th {
        vertical-align: top;
    }
    .queries-table td > div {
        margin-bottom: 6px;
    }
    .highlight pre {
        margin: 0;
        white-space: pre-wrap;
    }
    .highlight .keyword {
        color: #8959A8;
        font-weight: bold;
    }
    .highlight .word {
        color: #222222;
    }
    .highlight .variable {
        color: #916319;
    }
    .highlight .symbol {
        color: #222222;
    }
    .highlight .comment {
        color: #999999;
    }
    .highlight .backtick {
        color: #718C00;
    }
    .highlight .string {
        color: #718C00;
    }
    .highlight .number {
        color: #F5871F;
        font-weight: bold;
    }
    .highlight .error {
        color: #C82829;
    }
</style>
