<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector $block */
/** @var \ClawRock\Debug\Model\DataCollector\TranslationDataCollector $collector */
$collector = $block->getCollector();
?>
<h2>Translation Metrics</h2>
<div class="metrics">
    <div class="metric">
        <span class="value"><?php echo $collector->countDefined(); ?></span>
        <span class="label">Defined messages</span>
    </div>
    <div class="metric">
        <span class="value"><?php echo $collector->countMissing(); ?></span>
        <span class="label">Missing messages</span>
    </div>
</div>

<h2>Translation Messages</h2>
<div class="sf-tabs">
    <div class="tab">
        <h3 class="tab-title">Defined <span class="badge"><?php echo $collector->countUniqueDefined(); ?></span></h3>
        <div class="tab-content">
            <p class="help">These messages are correctly translated into the given locale.</p>
            <?php if (!$collector->countDefined()): ?>
                <div class="empty">
                    <p>None of the used translation messages are defined for the given locale.</p>
                </div>
            <?php else: ?>
                <?php echo $block->renderTable($collector->getTranslatedPhrases(), ['Phrase', 'Translation']); ?>
            <?php endif ?>
        </div>
    </div>
    <div class="tab">
        <h3 class="tab-title">Missing <span class="badge"><?php echo $collector->countUniqueMissing(); ?></span></h3>
        <div class="tab-content">
            <p class="help">These messages aren't translated into the given locale.</p>
            <?php if (!$collector->countMissing()): ?>
                <div class="empty">
                    <p>There are no messages of this category.</p>
                </div>
            <?php else: ?>
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Phrase</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($collector->getMissingPhrases() as $phrase): ?>
                            <tr>
                                <td><?php echo $phrase; ?></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            <?php endif ?>
        </div>
    </div>
</div>
<style>
    tr.sf-toggle-content.sf-toggle-visible {
        display: table-row !important;
    }
</style>
