<?php /** @var \ClawRock\Debug\Block\Profiler\Renderer\ParametersRenderer $block */ ?>
<table class="<?php echo $block->getData('class') ?>">
    <thead>
        <?php $labels = $block->getLabels(); ?>
        <tr>
            <th scope="col" class="key"><?php echo isset($labels[0]) ? $labels[0] : 'Key' ?></th>
            <th scope="col"><?php echo isset($labels[1]) ? $labels[1] : 'Value' ?></th>
        </tr>
    </thead>
    <tbody>
        <?php /** @var \Zend\Stdlib\Parameters $parameters */ ?>
        <?php if ($parameters = $block->getParameters()): ?>
            <?php foreach ($parameters as $key => $value): ?>
                <tr>
                    <th><?php echo $key ?></th>
                    <td><?php echo $block->dump($value); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="2">No data</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
