<?php
/** @var \ClawRock\Debug\Block\Profiler\Renderer\TableRenderer $block */
$labels = $block->getLabels();
?>
<table class="<?php echo $block->getClass() ?>">
    <thead>
    <tr>
        <th scope="col" class="key"><?php echo $labels[0] ?? 'Key' ?></th>
        <th scope="col" class="key"><?php echo $labels[1] ?? 'Value' ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getItems() as $key => $value): ?>
        <tr>
            <th scope="row"><?php echo $key ?></th>
            <td><?php echo $block->dump($value); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
