<?php
/** @var \ClawRock\Debug\Block\Profiler\Menu $block */
$collector = $block->getCollector(\ClawRock\Debug\Model\DataCollector\ModelDataCollector::NAME);
$statusColor = $collector->getMetric('loop_load') ? 'error' : ($collector->getMetric('load') > $collector->getLoadCallThreshold() ? 'warning' : 'normal');
?>
<span class="label label-status-<?php echo $statusColor ?>">
    <span class="icon">
        <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/models.svg'); ?>" alt="Models"/>
    </span>
    <strong>Models</strong>
    <?php if ($collector->getMetric('loop_load')): ?>
        <span class="count">
            <span><?php echo $collector->getMetric('loop_load')?></span>
        </span>
    <?php endif; ?>
</span>
