<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector\Customer $block */
/** @var \ClawRock\Debug\Model\DataCollector\CustomerDataCollector $collector */
$collector = $block->getCollector();
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?>">
    <div class="sf-toolbar-icon">
        <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/customer.svg'); ?>"
             alt="Customer"/>
        <span class="sf-toolbar-value">
            <?php if ($collector->isLoggedIn()): ?>
                <?php echo $collector->getCustomerEmail(); ?>
            <?php else: ?>
                @guest
            <?php endif; ?>
        </span>
    </div>
    <div class="sf-toolbar-info">
        <?php if ($collector->isLoggedIn()): ?>
            <div class="sf-toolbar-info-piece">
                <b>Logged in as</b>
                <span><?php echo $collector->getCustomerEmail(); ?></span>
            </div>
            <div class="sf-toolbar-info-piece">
                <b>Name</b>
                <span>
                    <?php echo $collector->getCustomerName(); ?>&nbsp;
                    #<?php echo $collector->getCustomerId(); ?>
                </span>
            </div>
        <?php endif; ?>
        <div class="sf-toolbar-info-piece">
            <b>Customer Group</b>
            <span>
                <?php echo $collector->getCustomerGroupCode(); ?>&nbsp;
                #<?php echo $collector->getCustomerGroupId(); ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <b>Tax Class</b>
            <span>
                <?php echo $collector->getCustomerTaxClassName(); ?>&nbsp;
                #<?php echo $collector->getCustomerTaxClassId(); ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <b>Actions</b>
            <?php if ($collector->isLoggedIn()): ?>
                <span><a href="<?php echo $block->getLogoutUrl(); ?>">Logout</a></span>
            <?php else: ?>
                <span>
                    <a href="<?php echo $block->getLoginUrl(); ?>">Login</a>&nbsp;
                    <a href="<?php echo $block->getRegisterUrl(); ?>">Register</a>
                </span>
            <?php endif; ?>
        </div>
    </div>
</div>
