<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector\Database $block */
/** @var \ClawRock\Debug\Model\DataCollector\DatabaseDataCollector $collector */
$collector = $block->getCollector();
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?> sf-toolbar-status-normal">
    <a target="_blank" href="<?php echo $block->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/database.svg'); ?>"
                 alt="Database"/>
            <span class="sf-toolbar-value"><?php echo $collector->getQueryCount() ?></span>
            <span class="sf-toolbar-info-piece-additional-detail">
                <span class="sf-toolbar-label">in</span>
                <span class="sf-toolbar-value"><?php echo sprintf('%0.2f', $collector->getTotalTime()) ?></span>
                <span class="sf-toolbar-label">ms</span>
            </span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <b>Database Queries</b>
            <span class="sf-toolbar-status "><?php echo $collector->getQueryCount() ?></span>
        </div>
        <div class="sf-toolbar-info-piece">
            <b>Query time</b>
            <span><?php echo sprintf('%0.2f', $collector->getTotalTime()) ?> ms</span>
        </div>
    </div>
</div>
