<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector $block */
/** @var \ClawRock\Debug\Model\DataCollector\EventDataCollector $collector */
$collector = $block->getCollector();
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?>">
    <a target="_blank" href="<?php echo $block->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/event.svg'); ?>" alt="Event"/>
            <span class="sf-toolbar-value"><?php echo $collector->getObserversCount() ?></span>
            <span class="sf-toolbar-info-piece-additional-detail">
                <span class="sf-toolbar-label">in</span>
                <span class="sf-toolbar-value"><?php echo $collector->getTime() ?></span>
                <span class="sf-toolbar-label">ms</span>
            </span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece">
                <b>Events dispatched</b>
                <span><?php echo $collector->getEventsCount() ?></span>
            </div>
            <div class="sf-toolbar-info-piece">
                <b>Observers executed</b>
                <span><?php echo $collector->getObserversCount() ?></span>
            </div>
            <div class="sf-toolbar-info-piece">
                <b>Time</b>
                <span><?php echo $collector->getTime(); ?> ms</span>
            </div>
        </div>
    </div>
</div>
