<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector $block */
/** @var \ClawRock\Debug\Model\DataCollector\MemoryDataCollector $collector */
$collector = $block->getCollector();
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?> sf-toolbar-status-normal">
    <div class="sf-toolbar-icon">
        <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/memory.svg'); ?>" alt="Memory"/>
        <span class="sf-toolbar-value"><?php echo sprintf('%.1f', $collector->getMemoryUsage() / 1024 / 1024) ?></span>
        <span class="sf-toolbar-label">MB</span>
    </div>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <b>Peak memory usage</b>
            <span><?php echo sprintf('%.1f', $collector->getMemoryUsage() / 1024 / 1024) ?> MB</span>
        </div>
        <div class="sf-toolbar-info-piece">
            <b>PHP memory limit</b>
            <span><?php echo $collector->getMemoryLimit() == -1 ? 'Unlimited' : sprintf('%.0f MB', $collector->getMemoryLimit() / 1024 / 1024) ?></span>
        </div>
    </div>
</div>
