<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector $block */
/** @var \ClawRock\Debug\Model\DataCollector\PluginDataCollector $collector */
$collector = $block->getCollector();
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?>">
    <a target="_blank" href="<?php echo $block->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/plugin.svg'); ?>" alt="Event"/>
            <span class="sf-toolbar-value"><?php echo $collector->getPluginsCount() ?></span>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-piece">
            <b>Before plugins</b>
            <span class="sf-toolbar-status">
                 <?php echo $collector->getBeforePluginsCount() ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <b>Around plugins</b>
            <span class="sf-toolbar-status">
                 <?php echo $collector->getAroundPluginsCount() ?>
            </span>
        </div>
        <div class="sf-toolbar-info-piece">
            <b>After plugins</b>
            <span class="sf-toolbar-status">
                 <?php echo $collector->getAfterPluginsCount() ?>
            </span>
        </div>
    </div>
</div>
