<?php
/** @var ClawRock\Debug\Block\Profiler\Collector\Request $block */
/** @var \ClawRock\Debug\Model\DataCollector\RequestDataCollector $collector */
$collector = $block->getCollector();
/** @var string $token */
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?> sf-toolbar-status-normal ">
    <a target="_blank" href="<?php echo $block->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <span class="sf-toolbar-status sf-toolbar-status-<?php echo $collector->getStatusColor(); ?>">
                <?php echo $collector->getStatusCode() ?>
            </span>
            <?php if ($collector->getFullActionName()): ?>
                <?php if ($collector->getRedirect()): ?>
                    <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/redirect.svg'); ?>"
                         class="redirect-img" alt="Redirect"/>
                <?php endif; ?>
                <span class="sf-toolbar-label">
                    <?php echo $collector->getMethod() !== 'GET' ? $collector->getMethod() : '' ?>@
                </span>
                <span class="sf-toolbar-value sf-toolbar-info-piece-additional">
                    <?php echo $collector->getFullActionName() ?>
                </span>
            <?php else: ?>
                <span class="sf-toolbar-label">@</span>
                <span class="sf-toolbar-value sf-toolbar-info-piece-additional">n/a</span>
            <?php endif; ?>
        </div>
    </a>
    <div class="sf-toolbar-info">
        <div class="sf-toolbar-info-group">
            <div class="sf-toolbar-info-piece">
                <b>HTTP status</b>
                <span><?php echo $collector->getStatusCode() ?></span>
            </div>
            <div class="sf-toolbar-info-piece">
                <b>FPC Hit</b>
                <?php if ($collector->isFPCHit()): ?>
                    <span class="sf-toolbar-status sf-toolbar-status-green">Yes</span>
                <?php else:?>
                    <span class="sf-toolbar-status">No</span>
                <?php endif;?>
            </div>

            <?php if (!$collector->isFPCHit()) : ?>
                <div class="sf-toolbar-info-piece">
                    <b>Module</b><span><?php echo $collector->getControllerModule() ?></span>
                </div>
                <div class="sf-toolbar-info-piece">
                    <b>Controller</b>
                    <span><?php echo $collector->getControllerName() ?>\<?php echo $collector->getActionName() ?> </span>
                </div>
                <div class="sf-toolbar-info-piece">
                    <b>Full action name</b>
                    <span><?php echo $collector->getFullActionName(); ?></span>
                </div>
            <?php endif; ?>
        </div>

        <?php if ($redirect = $collector->getRedirect()): ?>
            <div class="sf-toolbar-info-group">
                <div class="sf-toolbar-info-piece">
                    <b>
                        <span class="sf-toolbar-redirection-status sf-toolbar-status-yellow">
                            <?php echo $redirect['status_code'] ?>
                        </span>
                        Redirect from
                    </b>
                    <span>
                        (<a target="_blank" href="<?php echo $block->getProfilerUrl($redirect['token']) ?>">
                            <?php echo $redirect['token'] ?>
                        </a>)
                    </span>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
