<?php
/** @var \ClawRock\Debug\Block\Profiler\Collector\Time $block */
/** @var \ClawRock\Debug\Model\DataCollector\TimeDataCollector $collector */
$collector = $block->getCollector();
$token = $block->getToken();
?>
<div class="sf-toolbar-block sf-toolbar-block-<?php echo $collector->getCollectorName() ?> sf-toolbar-status-normal">
    <a target="_blank" href="<?php echo $block->getCollectorUrl($token, $collector); ?>">
        <div class="sf-toolbar-icon">
            <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/collector/time.svg'); ?>" alt="Time"/>
            <span class="sf-toolbar-value"><?php echo sprintf('%0.0f', $collector->getDuration()) ?></span>
            <span class="sf-toolbar-label">ms</span>
        </div>
        <div class="sf-toolbar-info">
            <div class="sf-toolbar-info-piece">
                <b>Total Time</b>
                <span><?php echo sprintf('%0.0f', $collector->getDuration()) ?> ms</span>
            </div>
        </div>
    </a>
</div>
