<?php
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \ClawRock\Debug\Model\View\Menu $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isActive($block->getCollectorName())): ?>
    <li class="request<?= $viewModel->isCurrentPanel($block->getCollectorName()) ? ' selected' : '' ?>">
        <a href="<?= $escaper->escapeUrl($viewModel->getProfilerUrl($block->getCollectorName())); ?>">
            <span class="label">
                <span class="icon">
                    <img src="
                    <?= $escaper->escapeUrl(
                        $block->getViewFileUrl('ClawRock_Debug::images/collector/redirect.svg')
                    ); ?>
                    " alt="<?= $escaper->escapeHtmlAttr(__('Request / Response')); ?>"/>
                </span>
                <strong><?= $escaper->escapeHtml(__('Request / Response')); ?></strong>
            </span>
        </a>
    </li>
<?php endif; ?>
