<?php
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<table>
    <thead>
        <tr>
            <th scope="col" class="key"><?= $escaper->escapeHtml(__('Key')); ?></th>
            <th scope="col"><?= $escaper->escapeHtml(__('Value')); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php /** @var \Zend\Stdlib\Parameters $parameters */ ?>
        <?php if ($parameters = $block->getParameters()): ?>
            <?php foreach ($parameters as $key => $value): ?>
                <tr>
                    <th><?= /* @noEscape */ $key ?></th>
                    <td><?= /* @noEscape */ $block->getVarRenderer()->render($value); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="2"><?= $escaper->escapeHtml(__('No data')); ?></td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
