<?php
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \ClawRock\Debug\Model\ValueObject\Redirect $redirect
 */
$redirect = $block->getRedirect();
?>
<dl class="metadata">
    <dt>
        <span class="label">
            <?= /* @noEscape */ $redirect->getStatusCode() ?>
        </span>
        <?= $escaper->escapeHtml(__('Redirect from')) ?>
    </dt>
    <dd>
        <?= /* @noEscape */ $redirect->getMethod() ?>
        <a href="<?= $escaper->escapeUrl($block->getProfilerUrl()) ?>">
            <?= /* @noEscape */ $redirect->getToken() ?>
        </a>
    </dd>
</dl>
