<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var \ClawRock\Debug\Model\View\Toolbar $vm */ ?>
<?php $vm = $block->getViewModel(); ?>
<?php $token = $vm->getToken(); ?>

<div id="sfMiniToolbar-<?= /* @noEscape */ $token; ?>" class="sf-minitoolbar" data-no-turbolink>
    <a href="#" title="<?= $block->escapeHtml(__('Debug Toolbar')) ?>" id="sfToolbarMiniToggler-<?= /* @noEscape */ $token; ?>" tabindex="-1" accesskey="D">
        <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/clawrock.svg'); ?>" alt="ClawRock"/>
    </a>
</div>
<div id="sfToolbarClearer-<?= /* @noEscape */ $token; ?>" class="sf-toolbar-clearer"></div>
<div id="sfToolbarMainContent-<?= /* @noEscape */ $token; ?>" class="sf-toolbarreset clear-fix" data-no-turbolink>
    <div class="sf-toolbar-block sf-toolbar-block-clawrock sf-toolbar-status-normal">
        <a target="_blank" href="http://clawrock.com">
            <div class="sf-toolbar-icon">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/clawrock.svg'); ?>" alt="ClawRock"/>
            </div>
        </a>
    </div>
    <?php /** @var \Magento\Framework\View\Element\Template $collectorBlock */ ?>
    <?php foreach ($vm->getCollectorBlocks() as $collectorBlock): ?>
        <?= $collectorBlock->toHtml(); ?>
    <?php endforeach; ?>
    <a href="#" class="hide-button" id="sfToolbarHideButton-<?= /* @noEscape */ $token; ?>" title="<?= $block->escapeHtml(__('Close Toolbar')) ?>" tabindex="-1" accesskey="D">
        <img src="<?= /* @noEscape */ $block->getViewFileUrl('ClawRock_Debug::images/icon/close.svg'); ?>" alt="<?= $block->escapeHtml(__('Close')) ?>">
    </a>
</div>
