<?php /** @var \ClawRock\Debug\Block\Profiler\Search $block */ ?>
<a href="#" class="visible-small" onclick="Sfjs.toggleClass(document.getElementById('sidebar'), 'expanded'); return false;">
    <span class="icon">
        <img src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/icon/menu.svg'); ?>" alt="Menu"/>
    </span>
</a>
<a class="btn btn-sm" href="<?php echo $block->getUrl('_debug/profiler/search', ['limit' => 10]) ?>">Last 10</a>
<a class="btn btn-sm" href="<?php echo $block->getUrl('_debug/profiler/info/token/latest'); ?>">Latest</a>
<a class="sf-toggle btn btn-sm" data-toggle-selector="#sidebar-search" <?php echo $block->isExpanded() ? 'data-toggle-initial="display"' : ''; ?>>
    <img width="24" height="24" src="<?php echo $block->getViewFileUrl('ClawRock_Debug::images/icon/search.svg'); ?>" alt="Search"/>
    <span class="hidden-small">Search</span>
</a>

<div id="sidebar-search" class="sf-toggle-content sf-toggle-hidden">
    <form action="<?php echo $block->getUrl('_debug/profiler/search'); ?>" method="get">
        <div class="form-group">
            <label for="ip">IP</label>
            <input type="text" name="ip" id="ip" value="<?php echo $block->getParam('ip'); ?> ">
        </div>
        <div class="form-group">
            <label for="method">Method</label>
            <select name="method" id="method">
                <option value="">Any</option>
                <?php foreach ($block->getMethods() as $method): ?>
                    <option <?php echo $block->paramSelected('method', $method); ?>><?php echo $method ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <label for="status_code">Status</label>
            <input type="number" name="status_code" id="status_code"
                   value="<?php echo $block->getParam('status_code'); ?>">
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" name="url" id="url" value="<?php echo $block->getParam('url'); ?>">
        </div>
        <div class="form-group">
            <label for="token">Token</label>
            <input type="text" name="_token" id="token" value="<?php echo $block->getParam('_token'); ?>">
        </div>
        <div class="form-group">
            <label for="start">From</label>
            <input type="date" name="start" id="start" value="<?php echo $block->getParam('start'); ?>">
        </div>
        <div class="form-group">
            <label for="end">Until</label>
            <input type="date" name="end" id="end" value="<?php echo $block->getParam('end'); ?>">
        </div>
        <div class="form-group">
            <label for="limit">Results</label>
            <select name="limit" id="limit">
                <?php foreach ($block->getLimits() as $limit): ?>
                    <option <?php echo $block->paramSelected('limit', $limit); ?>>
                        <?php echo $limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-sm">Search</button>
        </div>
    </form>
</div>
